config/routes.rb
Moorkit::Application.routes.draw do
  use_doorkeeper
  mount API::Root => '/'
  mount Resque::Server.new, :at => "/resque"

  get 'welcome/index'
  root to: 'welcome#index'

  get 'auth/:provider/callback', to: 'authentications#create'
  get 'signout', to: 'authentications#destroy', as: 'signout'

end

app/models/api_request.rb
class ApiRequest < ActiveRecord::Base
  serialize :payload, HashSerializer
  serialize :headers, HashSerializer
  store_accessor :headers, :authorization, :content_type, :accept, :cookie, :host
end

app/models/pipl_result.rb
class PiplResult < ActiveRecord::Base
  belongs_to :members
  serialize :request, HashSerializer
  serialize :response, HashSerializer
  store_accessor :response, :http_status_code, :person_count, :search_id, :person
end

app/models/user.rb
class User < ActiveRecord::Base
  serialize :details, HashSerializer
  store_accessor :details, :traits
  has_many :user_authentications
end

app/models/user_authentication.rb
class UserAuthentication < ActiveRecord::Base
  serialize :data, HashSerializer
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/authentications_controller.rb
require 'moorkit/user_authentication'

class AuthenticationsController < ApplicationController
  def create

    auth_payload = entitize_auth_hash(auth_hash)
    user = find_user(auth_payload)
    user = create_user(auth_payload) if user.nil?
    set_current_user(user)
    redirect_to root_path
  end

  def failure
    render json: auth_hash.to_json
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end

  def entitize_auth_hash(hsh)
    Moorkit::UserAuthentication.entitize_auth_hash_context.call(auth_hash: hsh)
  end

  def find_user(payload)
    Moorkit::UserAuthentication.find_user_context.call(auth_payload: payload)
  end

  def create_user(payload)
    Moorkit::UserAuthentication.create_user_context.call(auth_payload: payload)
  end

  def set_current_user(user)
    session[:user_id] = user.id
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Moorkit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Moorkit</h1>
<p>
  <h2>Authentication</h2>
  <% if current_user %>
    Logged in as <%= [current_user.first_name, current_user.last_name].join(" ") %>
    <%= link_to "Log Out", signout_path %>
  <% else %>
    Login with:
    <% [:developer, :google, :facebook, :linkedin].each do |prov| %>
      <%= link_to prov.to_s.capitalize, "/auth/#{prov}" %>
    <% end %>
  <% end %>
</p>
<p>
  <h2>Segment</h2>
  <%= form_tag('/api/v1/webhooks/segment.json') do %>
    <%= text_field_tag(:email, nil, placeholder: 'someone@gmail.com' ) %>
    <%= submit_tag('Submit') %>
  <% end %>
</p>
<p>
  <h2>Other</h2>
  <a href="https://www.github.com/ac21/moorkit">Check me out</a>
</p>